### ISSUE TITLE
Find npm table representation that supports pagination

### ISSUE THREAD

**Issue by dh3wr** [dapnet-core/web#2]
As the API support pagination, the current implementation of the table representation of the data of users, rubrics, transmitters and nodes shall be change to support pagination. First google search did not show any suitable candidates. Maybe a self-implementation with custom "forward" and "backward" buttons is necessary?

**Comment by dh3wr** [comment]
https://vuetifyjs.com/en/components/data-tables#example-server

**Comment by 7h0ma5** [comment]
Hier hatte ich sowas schon mal implementiert mit CouchDB:

https://github.com/7h0ma5/CloudShack/blob/vue/webapp/src/components/Logbook.vue

**Comment by dh3wr** [comment]
Da werde ich so einiges abschauen...

**Comment by dh3wr** [comment]
Done long time ago...
